services:
  web:
    container_name: web
    image: milssky/cicd_test:latest
    restart: always
  nginx:
    image: nginx:1.24.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
