name: cicd_test_deploy

on: [push]

jobs:
  test_connect:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: uname -a
