name: cicd_test_deploy

on: [push]

jobs:
  tests:
    name: Pytest
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Setup dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: pytest