name: cicd_test_deploy

on: [push]

jobs:
  test_connect:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Execute ssh commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          script: |
            uname -a
